# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AVR_CONFIG.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

PORTA={"PIN0":"DIO_PULL_UP\n","PIN1":"DIO_PULL_UP\n","PIN2":"DIO_PULL_UP\n","PIN3":"DIO_PULL_UP\n","PIN4":"DIO_PULL_UP\n","PIN5":"DIO_PULL_UP\n","PIN6":"DIO_PULL_UP\n","PIN7":"DIO_PULL_UP\n"}
PORTB={"PIN0":"DIO_PULL_UP\n","PIN1":"DIO_PULL_UP\n","PIN2":"DIO_PULL_UP\n","PIN3":"DIO_PULL_UP\n","PIN4":"DIO_PULL_UP\n","PIN5":"DIO_PULL_UP\n","PIN6":"DIO_PULL_UP\n","PIN7":"DIO_PULL_UP\n"}
PORTC={"PIN0":"DIO_PULL_UP\n","PIN1":"DIO_PULL_UP\n","PIN2":"DIO_PULL_UP\n","PIN3":"DIO_PULL_UP\n","PIN4":"DIO_PULL_UP\n","PIN5":"DIO_PULL_UP\n","PIN6":"DIO_PULL_UP\n","PIN7":"DIO_PULL_UP\n"}
PORTD={"PIN0":"DIO_PULL_UP\n","PIN1":"DIO_PULL_UP\n","PIN2":"DIO_PULL_UP\n","PIN3":"DIO_PULL_UP\n","PIN4":"DIO_PULL_UP\n","PIN5":"DIO_PULL_UP\n","PIN6":"DIO_PULL_UP\n","PIN7":"DIO_PULL_UP\n"}
PortDic = {"PORTA": ["DDRA", PORTA], "PORTB": ["DDRB", PORTB], "PORTC": ["DDRC", PORTC], "PORTD": ["DDRD", PORTD]}

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(696, 550)
        self.genBtn = QtWidgets.QPushButton(Form)
        self.genBtn.setGeometry(QtCore.QRect(210, 500, 231, 28))
        self.genBtn.setObjectName("genBtn")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(410, 150, 131, 51))
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(30, 450, 621, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 410, 101, 41))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(170, 0, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Output_groupBox = QtWidgets.QGroupBox(Form)
        self.Output_groupBox.setGeometry(QtCore.QRect(360, 160, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Output_groupBox.setFont(font)
        self.Output_groupBox.setObjectName("Output_groupBox")
        self.radioButton_5 = QtWidgets.QRadioButton(self.Output_groupBox)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 40, 95, 20))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.Output_groupBox)
        self.radioButton_6.setGeometry(QtCore.QRect(130, 40, 95, 20))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setObjectName("radioButton_6")
        self.Input_groupBox_2 = QtWidgets.QGroupBox(Form)
        self.Input_groupBox_2.setGeometry(QtCore.QRect(360, 70, 311, 80))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Input_groupBox_2.setFont(font)
        self.Input_groupBox_2.setObjectName("Input_groupBox_2")
        self.PullUp_radioButton = QtWidgets.QRadioButton(self.Input_groupBox_2)
        self.PullUp_radioButton.setGeometry(QtCore.QRect(10, 30, 95, 20))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.PullUp_radioButton.setFont(font)
        self.PullUp_radioButton.setObjectName("PullUp_radioButton")
        self.PullDown_radioButton_2 = QtWidgets.QRadioButton(self.Input_groupBox_2)
        self.PullDown_radioButton_2.setGeometry(QtCore.QRect(130, 30, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.PullDown_radioButton_2.setFont(font)
        self.PullDown_radioButton_2.setObjectName("PullDown_radioButton_2")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(220, 70, 121, 151))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.Input_radioButton_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.Input_radioButton_3.setGeometry(QtCore.QRect(20, 30, 95, 20))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Input_radioButton_3.setFont(font)
        self.Input_radioButton_3.setObjectName("Input_radioButton_3")
        self.Output_radioButton_4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.Output_radioButton_4.setGeometry(QtCore.QRect(20, 90, 95, 20))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Output_radioButton_4.setFont(font)
        self.Output_radioButton_4.setObjectName("Output_radioButton_4")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 70, 151, 151))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.portcombo = QtWidgets.QComboBox(self.groupBox_4)
        self.portcombo.setGeometry(QtCore.QRect(10, 40, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.portcombo.setFont(font)
        self.portcombo.setObjectName("portcombo")
        self.portcombo.addItem("")
        self.portcombo.addItem("")
        self.portcombo.addItem("")
        self.portcombo.addItem("")
        self.pincombo = QtWidgets.QComboBox(self.groupBox_4)
        self.pincombo.setGeometry(QtCore.QRect(10, 100, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pincombo.setFont(font)
        self.pincombo.setObjectName("pincombo")
        self.pincombo.addItem("")
        self.pincombo.addItem("")
        self.pincombo.addItem("")
        self.pincombo.addItem("")
        self.pincombo.addItem("")
        self.pincombo.addItem("")
        self.pincombo.addItem("")
        self.pincombo.addItem("")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 280, 621, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 240, 161, 16))
        self.label_3.setObjectName("label_3")
        self.newBtn = QtWidgets.QPushButton(Form)
        self.newBtn.setGeometry(QtCore.QRect(40, 330, 93, 28))
        self.newBtn.setObjectName("newBtn")
        self.saveBtn = QtWidgets.QPushButton(Form)
        self.saveBtn.setGeometry(QtCore.QRect(440, 330, 93, 28))
        self.saveBtn.setObjectName("saveBtn")
        self.loadBtn = QtWidgets.QPushButton(Form)
        self.loadBtn.setGeometry(QtCore.QRect(550, 330, 101, 31))
        self.loadBtn.setObjectName("loadBtn")

        self.retranslateUi(Form)

        self.Input_radioButton_3.clicked['bool'].connect(self.Output_groupBox.setDisabled) # type: ignore
        self.Output_radioButton_4.clicked['bool'].connect(self.Input_groupBox_2.setDisabled) # type: ignore
        self.Output_radioButton_4.clicked['bool'].connect(self.Output_groupBox.setEnabled) # type: ignore
        self.Input_radioButton_3.clicked['bool'].connect(self.Input_groupBox_2.setEnabled) # type: ignore

        self.genBtn.clicked.connect(self.generate)
        self.saveBtn.clicked.connect(self.saveBtnHandle)
        self.loadBtn.clicked.connect(self.loadBtnHandle)
        self.newBtn.clicked.connect(self.newBtnHandle)
        self.portcombo.highlighted.connect(self.updateDic)
        self.pincombo.highlighted.connect(self.updateDic)
        self.portcombo.currentIndexChanged.connect(self.updateHandle)
        self.pincombo.currentIndexChanged.connect(self.updateHandle)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def newBtnHandle(self):
      self.configNameEdit.setText('')
      for port in PortDic:
        for pin in PortDic[port][1]:
          PortDic[port][1][pin] = "DIO_PULL_UP\n"
      self.updateHandle()
      return
    def updateHandle(self):
      if (PortDic[self.portcombo.currentText()][1][self.pincombo.currentText()].strip() == "DIO_HIGH"):
        self.Output_radioButton_4.setChecked(True)
        self.Input_groupBox_2.setDisabled(True)
        self.Output_groupBox.setEnabled(True)
        self.radioButton_5.setChecked(True)
      
      elif (PortDic[self.portcombo.currentText()][1][self.pincombo.currentText()].strip() == "DIO_LOW"):
        self.Output_radioButton_4.setChecked(True)
        self.Input_groupBox_2.setDisabled(True)
        self.Output_groupBox.setEnabled(True)
        self.radioButton_6.setChecked(True)
        
      elif (PortDic[self.portcombo.currentText()][1][self.pincombo.currentText()].strip() == "DIO_HIGH_IMPEDANCE"):
        self.Input_radioButton_3.setChecked(True)
        self.Input_groupBox_2.setEnabled(True)
        self.Output_groupBox.setDisabled(True)
        self.PullDown_radioButton_2.setChecked(True)
      
      else:
        self.Input_radioButton_3.setChecked(True)
        self.Input_groupBox_2.setEnabled(True)
        self.Output_groupBox.setDisabled(True)
        self.PullUp_radioButton.setChecked(True)
      return
    def loadBtnHandle(self):
    
      if self.lineEdit_2.text() != '':
        ConfigFileName = self.lineEdit_2.text()
      else:
        return
      LoadFile = open(ConfigFileName, 'r')
      for line in LoadFile:
        configList = line.split()
        PortDic[configList[0]][1][configList[1]] = configList[2]
      self.updateHandle()
      LoadFile.close()
      return
    def saveBtnHandle(self):
      self.updateDic()
      if self.lineEdit_2.text() != '':
        ConfigFileName = self.lineEdit_2.text()
      else:
        ConfigFileName = 'DefaultConfig.txt'
      SaveFile = open(ConfigFileName, 'w')
      for port in PortDic:
        for pin in PortDic[port][1]:
          SaveFile.write('\n'+port + ' ' + pin + ' ' + PortDic[port][1][pin])
      SaveFile.close()
      return
    def updateDic(self): 
      if self.outputRadioBtn.isChecked():
        if self.highRadioBtn.isChecked():
          PortDic[self.portcombo.currentText()][1][self.pincombo.currentText()] = "DIO_HIGH\n"
        else:
          PortDic[self.portcombo.currentText()][1][self.pincombo.currentText()] = "DIO_LOW\n"

      else:
        if self.pullRadioBtn.isChecked():
          PortDic[self.portcombo.currentText()][1][self.pincombo.currentText()] = "DIO_PULL_UP\n"
        else:
          PortDic[self.portcombo.currentText()][1][self.pincombo.currentText()] = "DIO_HIGH_IMPEDANCE\n"
      return

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.genBtn.setText(_translate("Form", "Generate"))
        self.label_2.setText(_translate("Form", "File output path "))
        self.label_4.setText(_translate("Form", "AVR Configurator tool By Mostafa Ahmed"))
        self.Output_groupBox.setTitle(_translate("Form", "Output options"))
        self.radioButton_5.setText(_translate("Form", "HIGH"))
        self.radioButton_6.setText(_translate("Form", "LOW"))
        self.Input_groupBox_2.setTitle(_translate("Form", "Input optipons"))
        self.PullUp_radioButton.setText(_translate("Form", "PULL UP"))
        self.PullDown_radioButton_2.setText(_translate("Form", "PULL DOWN"))
        self.groupBox_3.setTitle(_translate("Form", "Pin Direction"))
        self.Input_radioButton_3.setText(_translate("Form", "INPUT"))
        self.Output_radioButton_4.setText(_translate("Form", "OUTPUT"))
        self.groupBox_4.setTitle(_translate("Form", "PORT   +    PIN"))
        self.portcombo.setItemText(0, _translate("Form", "PORTA"))
        self.portcombo.setItemText(1, _translate("Form", "PORTB"))
        self.portcombo.setItemText(2, _translate("Form", "PORTC"))
        self.portcombo.setItemText(3, _translate("Form", "PORTD"))
        self.pincombo.setItemText(0, _translate("Form", "PIN0"))
        self.pincombo.setItemText(1, _translate("Form", "PIN1"))
        self.pincombo.setItemText(2, _translate("Form", "PIN2"))
        self.pincombo.setItemText(3, _translate("Form", "PIN3"))
        self.pincombo.setItemText(4, _translate("Form", "PIN4"))
        self.pincombo.setItemText(5, _translate("Form", "PIN5"))
        self.pincombo.setItemText(6, _translate("Form", "PIN6"))
        self.pincombo.setItemText(7, _translate("Form", "PIN7"))
        self.label_3.setText(_translate("Form", "Configuration Utility"))
        self.newBtn.setText(_translate("Form", "New"))
        self.saveBtn.setText(_translate("Form", "Save"))
        self.loadBtn.setText(_translate("Form", "Load"))
    def generate(self):
      self.updateDic()
      if self.lineEdit.text() != '':
        DIO_H_Handler = open(self.lineEdit.text() + '\DIO.h', 'w')
        DIO_Handler = open(self.lineEdit.text() + '\DIO_config.h', 'w')
      else:
        DIO_Handler = open('DIO_config.h', 'w')
        DIO_H_Handler = open('DIO.h', 'w')

      DIO_H_Handler.write("/*\n")
      DIO_H_Handler.write(" * Written By: Mostafa Ahmed\n")
      DIO_H_Handler.write(" * Github: https://github.com/MostafaAhmedGit\n")
      DIO_H_Handler.write("*/\n")
      DIO_H_Handler.write("#ifndef DIO_H\n")
      DIO_H_Handler.write("#define DIO_H\n\n\n")
      DIO_H_Handler.write("#define DIO_IN                   0\n")
      DIO_H_Handler.write("#define DIO_OUT                  1\n\n")
      DIO_H_Handler.write("#define DIO_PULL_UP              1\n")
      DIO_H_Handler.write("#define DIO_HIGH_IMPEDANCE       0\n\n")
      DIO_H_Handler.write("#define DIO_HIGH                 1\n")
      DIO_H_Handler.write("#define DIO_LOW                  0\n\n")
      DIO_H_Handler.write("#endif\n")
      DIO_H_Handler.close()
      
      DIO_Handler.write("/*\n")
      DIO_Handler.write(" * Written By: Mostafa Ahmed\n")
      DIO_Handler.write(" * Github: https://github.com/MostafaAhmedGit\n")
      DIO_Handler.write("*/\n")
      DIO_Handler.write("#ifndef DIO_CFG_H\n")
      DIO_Handler.write("#define DIO_CFG_H\n\n\n")
      DIO_Handler.write("#endif\n")
      for port in PortDic:
        for pin in PortDic[port][1]:
          if PortDic[port][1][pin].strip() == "DIO_HIGH" or PortDic[port][1][pin].strip() == "DIO_LOW":
            DIO_Handler.write('#define DIO_'+PortDic[port][0]+'_'+pin+'      '+"DIO_OUT\n")
          else:
           DIO_Handler.write('#define DIO_'+PortDic[port][0]+'_'+pin+'      '+"DIO_IN\n")
      
      DIO_Handler.write('\n\n\n')
    
      for port in PortDic:
       for pin in PortDic[port][1]:
          DIO_Handler.write('#define DIO_'+port+'_'+pin+'     '+PortDic[port][1][pin])
      
      DIO_Handler.write("\n\n#endif\n")
      DIO_Handler.close()
     #return
    
    
    def updateDic(self): 
      if self.Output_radioButton_4.isChecked():
        if self.radioButton_5.isChecked():
          PortDic[self.portcombo.currentText()][1][self.pincombo.currentText()] = "DIO_HIGH\n"
        else:
          PortDic[self.portcombo.currentText()][1][self.pincombo.currentText()] = "DIO_LOW\n"

      else:
        if self.PullUp_radioButton.isChecked():
          PortDic[self.portcombo.currentText()][1][self.pincombo.currentText()] = "DIO_PULL_UP\n"
        else:
          PortDic[self.portcombo.currentText()][1][self.pincombo.currentText()] = "DIO_HIGH_IMPEDANCE\n"
      return

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
